FROM container-vm-base

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN set -e \
    && apt update \
    && apt --no-install-recommends -y install \
    python3 \
    python3-dev \
    curl \
    binutils \
    && curl -sSL https://bootstrap.pypa.io/get-pip.py | python3 \
    && curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/bin \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
