FROM weiyang/container-vm

RUN set -e \
    && apt update \
    && apt --no-install-recommends -y install \
    glusterfs-client \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
